[General]
seed0 = 562
verbose = True
cpu_count = 1
backend = sequential
speed_of_light = 299792458

[Output]
output_path = /data/NSOARES/hide_seek/output_test/
file_fmt = bingo_tod_horn_{mode}_{date}.h5
calibration_file_fmt = CALIBRATION_{date}.txt
polarizations = PXX

[Telescope]
telescope_latitude = -7.0
telescope_longitude = -38.0
telescope_elevation = 0.0

[Beam]
beam_profile_provider = hide.beam.gaussian_fwhm
beam_frequency_min = 960
beam_frequency_max = 1260
beam_number_channels = 30
beam_decimals = 2
beam_nside = 256
beam_response = 1
beam_elevation = 5
beam_azimut = 5
dish_diameter = 40.0
fwhm_0 = 0.0116
zernike_coefficients_file_name = DoubleRectangular_hornX_displacementY.fits
interpolation_scheme = nearest

[ScanningStrategy]
scanning_strategy_provider = hide.strategy.drift_scan
strategy_start = 2020-03-01-00:00:00
strategy_end = 2020-03-01-23:59:59
strategy_step_size = 0.1
time_range = 3600
coord_step_size = 0.1
alt_delta = 0.0
altitude_max_pos = 90.0

[AstroSignal]
astro_signal_provider = hide.astro.hi_sky
# FG_I_256_test.fits
astro_signal_file_name = FG_I_256_960mhz1260mhz_30bins_full_L0.fits
astro_signal_freq_file_name = oldfreqs_bingo.fits
cache_astro_signals = True

[EarthSignal]
earth_signal_provider = hide.earth.constant
earth_signal_flux = 0

[Background]
elevation_model = 0., 0., 0.

[Noise]
load_noise_template = True
temp_sys = 70000.0
delta_nu = 10000000.0
color_alpha = 0
color_fknee = 1
color_beta = 1
sample_freq = 1.0

[PostProcessing]
instrument = hide.spectrometer.fake_bingo_spectrometer

[RFI]
load_rfi_template = False
rfideltat = 5
rfideltaf = .5
rfiexponent = 2
rfienhance = 1.7
rfiday = 6.0, 22.0
rfidamping = 0.1

[RunHide]
bingo_model = 0
destination_path = /data/NSOARES/venvs/hs_env/lib/python3.8/site-packages/hide-0.1.0-py3.8.egg/hide/config/
working_path = /data/NSOARES/hide_seek/hide/hide/config/
az_in_file = /data/NSOARES/hide_seek/hide/azimuth.txt
al_in_file = /data/NSOARES/hide_seek/hide/altitude.txt
horn_i = 1
horn_f = 140
parallel = True
percentage_consider_core_unavailable = 20

[Hitmap]
seed0 = 757
percentage_consider_core_unavailable = 20
path = /data/NSOARES/hide_seek/output_test_parallel/

